/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('vue-element-plus-x')['Attachments']
    ElAlert: typeof import('element-plus')['ElAlert']
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElProgress: typeof import('element-plus')['ElProgress']
    ElTable: typeof import('element-plus')['ElTable']
    ElTableColumn: typeof import('element-plus')['ElTableColumn']
    Markdown: typeof import('vue-element-plus-x')['Markdown']
    Typewriter: typeof import('vue-element-plus-x')['Typewriter']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
