/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/demo-useXRequest copy.vue')['default']
    DemoUseBubble: typeof import('./src/components/demo-useBubble.vue')['default']
    DemoUseBubbleList: typeof import('./src/components/demo-useBubbleList.vue')['default']
    DemoUseChat: typeof import('./src/components/demo-useChat.vue')['default']
    DemoUseRequest: typeof import('./src/components/demo-useRequest.vue')['default']
    DemoUseSender: typeof import('./src/components/demo-useSender.vue')['default']
    DemoUseXChat: typeof import('./src/components/demo-useXChat.vue')['default']
    DemoUseXRequest: typeof import('./src/components/demo-useXRequest.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    UseRecord: typeof import('./src/components/useRecord.vue')['default']
  }
}
